# Generated by Django 4.1.7 on 2023-03-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_сakes_cake'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cake',
            new_name='Cakes',
        ),
    ]
