# Generated by Django 4.1.7 on 2023-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cake_cakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
