# Generated by Django 4.1.7 on 2023-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cakes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='composition',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
